name: java CI/CD
on: [push]
jobs:
  Compile_with_Maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Complie
        run: mvn compile
  Test_with_Maven:
    needs: Compile_with_Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        run: mvn test
      - name: upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: target/surefire-reports
  Assemble:
    needs: [Compile_with_Maven, Test_with_Maven]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: package
        run: mvn package
      - name: upload jar
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: target/*.jar

